Repository axibase/atsd, pull requests merged in 2018-08, with the labels that each got.

#743 aggregate
  api/data/series/aggregate.md
Labels: done

#739 webhook-refactor
  api/data/messages/webhook.md
  installation/README.md
  parsers/csv/examples/basic.md
Labels: done

#742 versioning
  versioning/README.md
Labels: done

#744 DateTime.add function
  rule-engine/object-datetime.md
Labels: done

#745 Dictionaries refactoring
  .dictionary-names
  .dictionary-other
  .spelling
  .travis-functions.sh
  .yaspellerrc
  administration/user-authentication.md
  administration/user-authorization.md
  changelogs/2017_09/README.md
  changelogs/2017_17/README.md
  changelogs/2017_27/README.md
  changelogs/2017_28/README.md
  changelogs/2017_33/README.md
  changelogs/2018_04/README.md
  integration/matlab/README.md
  integration/pentaho/report-designer/README.md
  integration/stata/README.md
  portals/freemarker.md
  rule-engine/notifications/custom-circleci.md
  rule-engine/notifications/custom-github.md
  rule-engine/notifications/custom-ifttt.md
  rule-engine/notifications/custom.md
  rule-engine/notifications/resources/custom-github-rule.xml
  sql/README.md
  sql/api-meta.md
  sql/examples/README.md
  sql/examples/filter-null-tag.md
  sql/examples/select-atsd_series.md
  sql/examples/select-pre-defined-columns.md
  sql/performance.md
Labels: done

#695 Workday Calendar explained
  administration/migration/README.md
  administration/migration/cluster.md
  administration/migration/container.md
  integration/spss/statistics/resources/index_calculation.htm
  rule-engine/condition.md
  rule-engine/derived.md
  rule-engine/functions-date.md
  rule-engine/functions.md
  rule-engine/images/button-download.png
  rule-engine/images/holiday-calendars.png
  rule-engine/images/timer-calendar.png
  rule-engine/object-datetime.md
  rule-engine/resources/calendars/aus.json
  rule-engine/resources/calendars/aut.json
  rule-engine/resources/calendars/bra.json
  rule-engine/resources/calendars/can.json
  rule-engine/resources/calendars/chn.json
  rule-engine/resources/calendars/deu.json
  rule-engine/resources/calendars/fra.json
  rule-engine/resources/calendars/gbr.json
  rule-engine/resources/calendars/isr.json
  rule-engine/resources/calendars/jpn.json
  rule-engine/resources/calendars/kor.json
  rule-engine/resources/calendars/rus.json
  rule-engine/resources/calendars/sgp.json
  rule-engine/resources/calendars/usa.json
  rule-engine/scheduled-rules.md
  rule-engine/window-fields.md
  rule-engine/workday-calendar-schema.md
  rule-engine/workday-calendar.md
Labels: done

#738 Updated RuleAlert object
  rule-engine/functions-alert-history.md
Labels: pending

#732 scheduled-rules-refactor
  rule-engine/images/last-open.png
  rule-engine/images/new-metric.png
  rule-engine/images/now-condition-new.png
  rule-engine/images/timer-metric-example.png
  rule-engine/scheduled-rules.md
Labels: pending

#701 Document is_workday and is_weekday
  sql/README.md
  sql/examples/filter-by-date.md
Labels: done

#749 discord-refactor
  rule-engine/notifications/discord.md
Labels: done

#748 user-authentication-refactor
  administration/user-authentication.md
Labels: done

#752 july-change-logs
  .dictionary-other
  changelogs/2018_07/README.md
Labels: done

#747 series-insert-refactor
  api/data/series/insert.md
Labels: done

#756 change-logs-refactor
  changelogs/README.md
  changelogs/images/button.png
  changelogs/images/change-log-visualization1.png
Labels: done

#755 added to_timezone function
  rule-engine/functions-date.md
  rule-engine/object-datetime.md
Labels: done

#760 window-fields-review
  rule-engine/window-fields.md
Labels: done

#762 Fixed links
  .travis-functions.sh
  changelogs/2018_jul/README.md
  changelogs/2018_jun/README.md
  rule-engine/window.md
  tutorials/getting-started-alert.md
Labels: done

#765 object-datetime-refactor
  rule-engine/object-datetime.md
Labels: done

#766 derived-refactor
  rule-engine/derived.md
Labels: done

#768 date-functions-refactor
  rule-engine/functions-date.md
Labels: done

#764 scheduled-rules-refactor
  rule-engine/scheduled-rules.md
Labels: done

#771 filter-by-date-refactor
  sql/examples/filter-by-date.md
Labels: done

#767 alert-history-refactor
  rule-engine/functions-alert-history.md
Labels: done

#772 user-authorization-refactor
  administration/images/collector-wizard-example.png
  administration/images/resource-viewer-wizard.png
  administration/images/wizard-data-user.png
  administration/images/wizard-example.png
  administration/images/wizard-resource-viewer.png
  administration/user-authorization.md
Labels: done

#770 sql-functions-refactor
  sql/README.md
Labels: done

#769 workday-calendar-refactor
  rule-engine/workday-calendar.md
Labels: done

#776 Support linkcheck config in .linkcheck-config.json
  .travis-functions.sh
Labels: pending

#774 search-refactor
  search/README.md
  search/images/search.png
  search/images/series-search1.png
Labels: done

#763 weather-parser-refactor
  parsers/csv/examples/images/halifax-1.png
  parsers/csv/examples/images/halifax-10.png
  parsers/csv/examples/images/halifax-2.png
  parsers/csv/examples/images/halifax-4.png
  parsers/csv/examples/images/halifax-5.png
  parsers/csv/examples/images/halifax-6.png
  parsers/csv/examples/images/halifax-7.png
  parsers/csv/examples/images/halifax-8.png
  parsers/csv/examples/images/halifax-9.png
  parsers/csv/examples/resources/air_quality_csv_parser.png
  parsers/csv/examples/resources/csv_halifax_config.png
  parsers/csv/examples/weather.md
Labels: done

#779 Use default link validator from npm instead of custom one from github repo
  .travis-functions.sh
Labels: done

#780 Freeze yaspeller version
  .travis-functions.sh
Labels: done

#781 linkcheck-update
  .linkcheck-config.json
Labels: done

#773 entity-groups-refactor
  configuration/entity_groups.md
  configuration/entity_views.md
  configuration/images/dual-list.png
  configuration/images/entity-groups-title.png
  configuration/images/entity-groups.png
  configuration/images/entity-view-add.png
  configuration/images/entity-views-menu.png
  configuration/images/expression.png
  configuration/images/settings-entity-groups.png
  configuration/images/text-list.png
  parsers/csv/examples/basic.md
  sql/README.md
Labels: done

#775 requirements-refactor
  administration/replication.md
  administration/requirements.md
  installation/README.md
  installation/other-distributions.md
  installation/redhat-centos-offline.md
  installation/redhat-centos-rpm.md
  installation/redhat-centos-yum.md
  installation/requirements.md
  installation/sles-offline.md
  installation/sles-rpm.md
  installation/troubleshooting.md
  installation/ubuntu-debian-apt.md
  installation/ubuntu-debian-deb.md
  installation/ubuntu-debian-offline.md
  toc.md
Labels: done

#778 email-refactor
  rule-engine/email.md
  rule-engine/images/email-message-composition-1.png
  rule-engine/images/email-message-composition-4.png
  rule-engine/images/email-message-composition-bottom.png
  rule-engine/images/email-message-composition-top.png
  rule-engine/images/email-tab-rule.png
Labels: done

#784 linkcheck-config
  .linkcheck-config.json
Labels: done

#783 Use atsd link whitelist for linkcheck for all repos
  .travis-functions.sh
Labels: done

#789 functions-overview
  changelogs/2018_may/README.md
  rule-engine/functions.md
Labels: done

#786 change-log-chart
  changelogs/README.md
  changelogs/images/change-tracker-portal.png
  changelogs/images/change-tracker-portal1.png
Labels: done

#788 Add some examples to entity search
  changelogs/2018_may/README.md
  search/entity-search.md
Labels: done

#790 lint
  .dictionary-names
  integration/scollector/README.md
  integration/scollector/scollector-startup.md
  integration/statsd/statsd-backend.md
  rule-engine/functions-link.md
  rule-engine/notifications/aws-api.md
  sql/scheduled-sql.md
Labels: done

#791 getting-started-refactor
  search/entity-search.md
  tutorials/getting-started-alert.md
  tutorials/getting-started-export.md
  tutorials/getting-started-insert.md
  tutorials/getting-started-portal.md
  tutorials/getting-started-sql.md
  tutorials/getting-started.md
  tutorials/resources/data-export.png
  tutorials/resources/series-type.png
  tutorials/resources/statsicon.png
Labels: done

#792 data-applications
  data-applications.md
  images/cross-filter.png
  images/data-monitor.png
  images/data-slider.png
  images/performance-viewer1.png
  images/power-meter-application.png
Labels: done

#709 installation-refactor
  .dictionary-other
  .linkcheck-config.json
  README.md
  administration/backup.md
  administration/support.md
  changelogs/2018_mar/README.md
  images/aws3.png
  images/centos.png
  images/cloudera2.png
  images/debian1.png
  images/docker2.png
  images/emrfs.png
  images/hadoop2.png
  images/install.png
  images/kub.png
  images/redhat1.png
  images/sles.png
  images/ubuntu2.png
  installation/README.md
  installation/images.md
  installation/images/portal-title.png
  installation/other-distributions.md
  installation/packages.md
  installation/redhat-centos-rpm.md
  installation/redhat-centos-yum.md
  installation/sles-offline.md
  installation/sles-rpm.md
  installation/ubuntu-debian-apt.md
  installation/ubuntu-debian-deb.md
  installation/verifying-installation.md
  integration/data-applications/README.md
  tutorials/getting-started.md
Labels: pending

#794 data-applications-lint
  .linkcheck-config.json
  integration/data-applications/README.md
Labels: done

#799 time-refactor-2
  rule-engine/window-fields.md
Labels: done

#798 data-slider
  integration/data-applications/data-slider.md
  integration/data-applications/images/data-slider-1.png
Labels: done

#800 data-monitor
  .linkcheck-config.json
  api/meta/README.md
  integration/data-applications/data-monitor.md
  integration/data-applications/images/ahead.png
  integration/data-applications/images/data-monitor.png
  integration/data-applications/images/lagging.png
  tutorials/getting-started.md
Labels: done

#803 getting-started-toc
  tutorials/getting-started.md
Labels: question

#804 action logging
  rule-engine/README.md
  rule-engine/images/action-log-menu.png
  rule-engine/images/email-log.png
  rule-engine/images/script-log.png
  rule-engine/images/webhook-log.png
Labels: done

#808 selecting-series
  .linkcheck-config.json
  portals/selecting-series.md
Labels: done

#810 exporting-data
  .linkcheck-config.json
  administration/compaction/atsd.md
  reporting/README.md
  reporting/ad-hoc-exporting.md
  reporting/export-url.md
  reporting/scheduled-exporting.md
Labels: done

#811 metric-search
  search/entity-search.md
  search/metric-search.md
Labels: done

#812 aggregation-functions
  api/data/aggregation.md
  api/data/series/examples/query-aggr-interpolate-delta.md
  api/data/series/group.md
  api/data/series/query.md
Labels: done

#815 db-message-last
  api/data/messages/query.md
  api/data/severity.md
  rule-engine/functions-message.md
Labels: done

#816 forecast-screenshots
  forecasting/README.md
  forecasting/resources/forecasts-1.png
  forecasting/resources/forecasts-2.png
  forecasting/resources/forecasts.png
  forecasting/resources/forecasts_2.png
Labels: done

#805 smoothing-series
  .dictionary-names
  .dictionary-other
  api/data/series/images/Delta.png
  api/data/series/images/Delta.svg
  api/data/series/images/alpha.svg
  api/data/series/images/avg.svg
  api/data/series/images/ema-evenly.svg
  api/data/series/images/ema1.svg
  api/data/series/images/n-equals-1.svg
  api/data/series/images/n-samples-with-dot.svg
  api/data/series/images/n-values-with-dot.svg
  api/data/series/images/n-values.svg
  api/data/series/images/rangeViaFactor.png
  api/data/series/images/rangeViaFactor.svg
  api/data/series/images/smooth-all.png
  api/data/series/images/smooth-avg.png
  api/data/series/images/smooth-ema.png
  api/data/series/images/smooth-title.png
  api/data/series/images/smoothed.svg
  api/data/series/images/smoothingFactor.svg
  api/data/series/images/tau.svg
  api/data/series/images/value-1.svg
  api/data/series/images/wavg.svg
  api/data/series/images/wtavg-weight.png
  api/data/series/images/wtavg.svg
  api/data/series/query.md
  api/data/series/smooth.md
Labels: done
