Repository axibase/atsd, pull requests merged in 2018-05, with the labels that each got.

#604 Permissions endpoint
  api/README.md
  api/data/README.md
  api/data/properties/type-query.md
  api/data/properties/url-query.md
  api/data/series/examples/url-query-csv-format.md
  api/data/series/url-query.md
  api/meta/entity-group/get-entities.md
  api/meta/entity-group/get.md
  api/meta/entity-group/list.md
  api/meta/entity/entity-groups.md
  api/meta/entity/get.md
  api/meta/entity/list.md
  api/meta/entity/metrics.md
  api/meta/entity/property-types.md
  api/meta/metric/get.md
  api/meta/metric/list.md
  api/meta/metric/series-tags.md
  api/meta/metric/series.md
  api/meta/misc/README.md
  api/meta/misc/permissions.md
  api/meta/misc/ping.md
  api/meta/misc/search.md
  api/meta/misc/version.md
Labels: reviewed

#600 April change logs
  changelogs/2018_04/README.md
  changelogs/README.md
Labels: refactored

#606 may-change-logs
  changelogs/2018_05/README.md
  changelogs/README.md
Labels: done

#605 Add portal Menu
  .vuepress/config.js
  sql/examples/sql-report.htm
  sql/scheduled-sql.md
Labels: done

#610 [Dev] anchors validator
  .travis-functions.sh
  .travis.yml
Labels: done
